[database]
host = "localhost"
port = "5432"
user = "postgres"
password = "admin"
database_name = "postgres"

[jwt]
secret = "GA=a48]zpEV[#F|W^oiw5Wy{}7$H7.?Q[RV!8Y?=-f v[7^VW`lLn$rB2jo@]ho2"

#[[rules]]
#name = "all"
#rule_set = [
#    ">5",
#    "<100",
#]